on:
  push:
    branches:
      - master
      - 15x
  pull_request:
    branches:
      - master
      - 15x
jobs:     
  linux:
    name: linux Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - run: |
          git lfs install
          git lfs pull
      
      - name: Install dep
        run: sudo apt update && sudo apt install libpulse-dev libglvnd-dev libx11-dev libopenal-dev libvulkan-dev libgl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev libgtk-3-dev ninja-build
        
      - name: Build
        run: python3 build.py
      
      - name: Prepare deploy
        run: |
          cp -Rvf Release/Sample Dev/release/
          cp -Rvf ResourceData/samples/* Dev/release/Sample/
          cp readme_* Dev/release/
          cp -Rvf docs/ Dev/release/
          
      - name: Upload all
        uses: actions/upload-artifact@v1
        with:
          name: EffekseerLinux
          path: Dev/release

        
  windows:
    name: windows Build
    runs-on: vs2017-win2016
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - run: |
         git lfs install
         git lfs pull
        
      - name: Build
        run: python build.py

      - name: Prepare deploy
        shell: bash
        run: |
          cp -Rvf Release/Sample Dev/release/
          cp -Rvf ResourceData/samples/* Dev/release/Sample/
          cp readme_* Dev/release/
          cp -Rvf docs/ Dev/release/
          
                
      - name: Upload all
        uses: actions/upload-artifact@v1
        with:
          name: EffekseerWindows
          path: Dev/release
          
          

                    
      
