on:
  push:
    branches:
      - master
      - 15x
  pull_request:
    branches:
      - master
      - 15x
jobs:     
  BuildTool:
    strategy:
      matrix:
        os: [ubuntu-latest,windows-latest]
        include:
          - os: ubuntu-latest
            name: "linux"
          - os: windows-latest
            name: "windows"
    name: Build on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 1
      - run: |
          git lfs install
          git lfs pull
      
      - name: Install Linux Dependencies
        if: matrix.name == 'linux'
        run: |
          wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.asc.gpg
          sudo mv microsoft.asc.gpg /etc/apt/trusted.gpg.d/
          wget -q https://packages.microsoft.com/config/ubuntu/18.04/prod.list 
          sudo mv prod.list /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt-get update
          sudo apt-get install -y  libpulse-dev libglvnd-dev libx11-dev libopenal-dev libvulkan-dev \
               libgl1-mesa-dev libgles2-mesa-dev libglu1-mesa-dev libgtk-3-dev ninja-build dotnet-sdk-3.1 \
               xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
        
      - name: Build
        run: python3 build.py
      
      - name: Prepare deploy
        run: |
          mkdir dist
          cp -Rvf Dev/release/*/publish/* dist/
          
      - name: Upload Release
        uses: actions/upload-artifact@v1
        with:
          name: Effekseer-${{ matrix.name }}
          path: dist

        
